"""Companion MGEF generation — aimed variants of vanilla magic effects.

Skyrim ships no fire-and-forget/aimed MGEF for plain value modifiers (Restore
Health on target, Damage Attribute, Weakness to X, Cure ...), so the mapping
tables resolve those TES4 effect codes to Alch*/self-delivery effects.  That is
fine for potions and touch spells, but an AIMED magic item whose effects all
lack a projectile is a HARD CRASH — not merely a dud cast, which is what this
docstring used to claim and what the CK warning ("Magic Item ... is AIMED but
has no Magic Effects with Projectiles assigned", 369 items) implies.
MagicItem::GetCostliestEffectItem skips every projectile-less effect when the
delivery is Aimed and returns null; the combat-AI item rating function then
dereferences that null.  Full exe trace and the vanilla census in
docs/magic_conversion_plan.md, Phase 3.

Fix: when an aimed ENCH/SPEL/SCRL ends up with no projectile-bearing effect,
synthesize ONE companion MGEF here — a clone of the vanilla effect the primary
effect resolved to, patched to Fire and Forget + Aimed + a projectile — and
swap it in for that first effect.  The remaining effects stay as mapped; they
apply on impact alongside it.

The 152-byte vanilla DATA blobs come from tes5_import/vanilla_mgef_data.py,
generated by tools/generators/gen_vanilla_mgef_table.py from the Skyrim.esm dump (end
users don't have references/).
"""
import struct
import threading

from .vanilla_mgef_data import MGEF_DATA_SIZE, VANILLA_MGEF_DATA
from .writer import pack_record, pack_string_subrecord, pack_subrecord

# MGEF DATA offsets (TES5, 152 bytes — see xEdit wbDefinitionsTES5 Magic Effect
# Data and the layout constants in tools/generators/gen_vanilla_mgef_table.py's source).
_OFF_FLAGS = 0x00
_OFF_COUNTER_COUNT = 0x14      # counter-effect count — must match ESCE entries
_OFF_PROJECTILE = 0x48
_OFF_CAST_TYPE = 0x50          # 0 constant, 1 fire and forget, 2 concentration
_OFF_DELIVERY = 0x54           # 0 self, 1 touch, 2 aimed, 3 target actor
_HOSTILE = 0x00000001

# Projectiles for the synthesized effects, picked from vanilla aimed MGEFs so
# the bolt has real art/flight data.  Hostile effects fly the ghostly bolt of
# dunTrevasSpectralArrowDamageFFAimed; beneficial ones the golden sunfire of
# TurnUndeadFFAimed25.
_PROJ_HOSTILE = 0x000AB23B     # dunTrevasSpectralArrowProjectile
_PROJ_BENEFICIAL = 0x0004BE35  # TurnProjectile01

# TES4 effect code -> display name ("DGHE" -> "Damage Health"), built from the
# export's own MGEF records so the synthesized effect is named what Oblivion
# called it on the item card.
_tes4_names: dict = {}

# (vanilla fid, tes4 code) -> generated MGEF fid.  Keyed per code so a Burden
# staff shows "Burden", not the name of whichever code shares its vanilla
# mapping.  Converters run in a thread pool, hence the lock.
_cache: dict = {}
_lock = threading.Lock()


def set_tes4_effect_names(mgef_records: list) -> None:
    """Register TES4 MGEF display names ({4-char code: FULL})."""
    from .text_reader import get_str
    _tes4_names.clear()
    _cache.clear()
    for rec in mgef_records:
        code = get_str(rec, 'EditorID')
        full = get_str(rec, 'FULL')
        if code and full:
            _tes4_names[code] = full


def has_projectile(mgef_fid: int) -> bool:
    """True if the MGEF launches a projectile.

    Three sources, because effect lists mix all three:
      * MGEFs the converter emitted for this plugin — since convert_MGEF
        landed these are the NORMAL answer from _resolve_mgef, and they are
        neither vanilla nor in _cache.  Treating them as projectile-less (the
        old behaviour) made this check useless for almost every record;
      * aimed clones this module generated, which always carry one;
      * vanilla Skyrim effects, read from the baked DATA table.
    """
    from .record_types.magic import emitted_projectile, is_emitted_mgef

    if is_emitted_mgef(mgef_fid):
        return emitted_projectile(mgef_fid) != 0

    entry = VANILLA_MGEF_DATA.get(mgef_fid)
    if entry is None:
        return mgef_fid in _cache.values()
    data = bytes.fromhex(entry[1])
    return struct.unpack_from('<I', data, _OFF_PROJECTILE)[0] != 0


def aimed_variant(mgef_fid: int, tes4_code: str, writer) -> int:
    """FormID of an aimed clone of ``mgef_fid``, generating it on first use.

    Returns 0 when the vanilla effect is unknown (nothing to clone).
    """
    entry = VANILLA_MGEF_DATA.get(mgef_fid)
    if entry is None or writer is None:
        return 0
    with _lock:
        key = (mgef_fid, tes4_code)
        cached = _cache.get(key)
        if cached:
            return cached

        edid, data_hex = entry
        data = bytearray(bytes.fromhex(data_hex))
        # A short blob means the generated table was built from a truncated
        # dump; writing it would emit an MGEF the CK/engine cannot read.
        if len(data) != MGEF_DATA_SIZE:
            raise ValueError(
                f'vanilla MGEF {mgef_fid:08X} ({edid}) DATA is {len(data)} '
                f'bytes, expected {MGEF_DATA_SIZE} — regenerate with '
                f'tools/generators/gen_vanilla_mgef_table.py')
        hostile = struct.unpack_from('<I', data, _OFF_FLAGS)[0] & _HOSTILE
        proj = _PROJ_HOSTILE if hostile else _PROJ_BENEFICIAL
        struct.pack_into('<I', data, _OFF_PROJECTILE, proj)
        struct.pack_into('<I', data, _OFF_CAST_TYPE, 1)
        struct.pack_into('<I', data, _OFF_DELIVERY, 2)
        # The clone carries no ESCE subrecords, so the counter-effect count
        # must be zeroed or the CK reads garbage counter slots.
        struct.pack_into('<I', data, _OFF_COUNTER_COUNT, 0)

        fid = writer.derive_formid('MGEF_AIMED', key)
        subs = pack_string_subrecord('EDID', f'TES4{tes4_code}{edid}Aimed')
        full = _tes4_names.get(tes4_code)
        if full:
            subs += pack_string_subrecord('FULL', full)
        subs += pack_subrecord('DATA', bytes(data))
        writer.add_record('MGEF', pack_record('MGEF', fid, 0, subs))
        _cache[key] = fid
        return fid
